services:
  backend1:
    image: ${DOCKER_USERNAME}/backend1:latest
    container_name: backend1
    env_file:
      - ./backend1/.env
    ports:
      - "5434:5434"
    networks:
      - semika-network
    depends_on:
      - postgres
  backend2:
    image: ${DOCKER_USERNAME}/backend2:latest
    container_name: backend2
    env_file:
      - ./backend2/.env
    ports:
      - "5435:5435"
    networks:
      - semika-network
    depends_on:
      - postgres
  frontend:
    image: ${DOCKER_USERNAME}/frontend:latest
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    networks:
      - semika-network
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - semika-network
networks:
  semika-network:
    driver: bridge